
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class CatatanHarianFrame extends javax.swing.JFrame {
    CatatanManager manager = new CatatanManager();

    /**
     * Creates new form CatatanHarianFrame
     */
    public CatatanHarianFrame() {
        initComponents();
        
        listCatatan.setModel(new DefaultListModel<String>());
        DefaultListModel<String> modelCatatan = new DefaultListModel<>();
        listCatatan.setModel(modelCatatan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaCatatan = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listCatatan = new javax.swing.JList<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        textAreaCatatan.setColumns(20);
        textAreaCatatan.setRows(5);
        jScrollPane2.setViewportView(textAreaCatatan);

        listCatatan.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCatatan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCatatanValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listCatatan);

        btnTambah.setBackground(new java.awt.Color(102, 255, 102));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(153, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 153, 0));
        btnSimpan.setText("Export");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 255, 0));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel1.setText("Judul");

        jLabel2.setText("Masukan Text");

        btnImport.setBackground(new java.awt.Color(102, 102, 255));
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSimpan)
                            .addComponent(btnTambah))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUbah)
                            .addComponent(btnImport))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKeluar)
                            .addComponent(btnHapus))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnImport)
                            .addComponent(btnKeluar))
                        .addGap(156, 156, 156))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
      String judul = JOptionPane.showInputDialog("Masukkan Judul Catatan:");
    String isi = textAreaCatatan.getText();
    if (judul != null && !judul.isEmpty()) {
        Catatan baru = new Catatan(judul, isi);
        manager.tambahCatatan(baru);
        listCatatan.setListData(manager.getCatatanList().stream().map(Catatan::getJudul).toArray(String[]::new)); // Perubahan di sini
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int selectedIndex = listCatatan.getSelectedIndex();
    if (selectedIndex != -1) {
        String judul = JOptionPane.showInputDialog("Masukkan Judul Baru:");
        String isi = textAreaCatatan.getText();
        Catatan baru = new Catatan(judul, isi);
        manager.ubahCatatan(selectedIndex, baru);
        listCatatan.setListData(manager.getCatatanList().stream().map(Catatan::getJudul).toArray(String[]::new)); // Perubahan di sini
    }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       int selectedIndex = listCatatan.getSelectedIndex();
    if (selectedIndex != -1) {
        manager.hapusCatatan(selectedIndex);
        
        // Update daftar catatan di JList
        listCatatan.setListData(manager.getCatatanList().stream().map(Catatan::getJudul).toArray(String[]::new));
        
        // Kosongkan JTextArea setelah judul dihapus
        textAreaCatatan.setText("");
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void listCatatanValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCatatanValueChanged
        int selectedIndex = listCatatan.getSelectedIndex();
    if (selectedIndex != -1) {
        Catatan selectedCatatan = manager.getCatatanList().get(selectedIndex);
        textAreaCatatan.setText(selectedCatatan.getIsi());
    }

    }//GEN-LAST:event_listCatatanValueChanged

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      int selectedIndex = listCatatan.getSelectedIndex();
    if (selectedIndex != -1) {
        // Mengambil judul catatan yang dipilih dari JList
        String judul = listCatatan.getModel().getElementAt(selectedIndex);
        
        // Membersihkan karakter yang tidak valid untuk nama file
        String namaFile = judul.replaceAll("[^a-zA-Z0-9\\s]", "").replace(" ", "_");
        
        // Dialog untuk memilih lokasi file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new File(namaFile + ".txt")); // Set judul catatan sebagai nama file default
        int option = fileChooser.showSaveDialog(this);
        
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            try (PrintWriter writer = new PrintWriter(new FileWriter(file))) {
                // Menyimpan judul dan isi catatan ke file teks
                writer.println("Judul Catatan: " + judul);
                writer.println("\nIsi Catatan:");
                writer.println(textAreaCatatan.getText());

                JOptionPane.showMessageDialog(this, "Catatan berhasil disimpan sebagai file TXT!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error menyimpan file: " + ex.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih catatan terlebih dahulu!");
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
         // Konfirmasi keluar
    int pilihan = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (pilihan == JOptionPane.YES_OPTION) {
        System.exit(0);  // Menutup aplikasi
    }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    int option = fileChooser.showOpenDialog(this);

    if (option == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            StringBuilder isiCatatan = new StringBuilder();
            String judul = null;

            // Pastikan JList menggunakan DefaultListModel
            if (listCatatan.getModel() instanceof DefaultListModel) {
                DefaultListModel<String> model = (DefaultListModel<String>) listCatatan.getModel();

                // Membaca file baris demi baris
                while ((line = reader.readLine()) != null) {
                    if (line.startsWith("Judul Catatan: ")) {
                        judul = line.substring(15); // Ambil judul catatan
                    } else if (line.startsWith("Isi Catatan:")) {
                        isiCatatan.setLength(0); // Kosongkan buffer isiCatatan untuk catatan baru
                    } else {
                        isiCatatan.append(line).append("\n"); // Tambahkan baris ke isiCatatan
                    }
                }

                // Tambahkan judul catatan ke JList, bahkan jika sudah ada sebelumnya
                if (judul != null && !judul.isEmpty()) {
                    model.addElement(judul); // Tambahkan judul ke JList
                    textAreaCatatan.setText(isiCatatan.toString()); // Tampilkan isi catatan di JTextArea
                    JOptionPane.showMessageDialog(this, "Catatan berhasil diimpor!");
                } else {
                    JOptionPane.showMessageDialog(this, "File tidak memiliki judul catatan yang valid!");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Model JList bukan DefaultListModel!");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error membaca file: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnImportActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatatanHarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatatanHarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatatanHarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatatanHarianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatatanHarianFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listCatatan;
    private javax.swing.JTextArea textAreaCatatan;
    // End of variables declaration//GEN-END:variables
}
